services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: superuser
      MINIO_ROOT_PASSWORD: superuser
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  spark-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-app
    depends_on:
      - minio

    environment:
      AWS_ACCESS_KEY_ID: superuser
      AWS_SECRET_ACCESS_KEY: superuser
      S3_ENDPOINT: http://minio:9000
    volumes:
      - ./data:/p1/data

volumes:
  minio_data: